tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "koekeishiya/formulae"

brew "bat"
brew "cowsay"
brew "exa"
brew "fzf"
brew "git"
brew "jq"
brew "ripgrep"
brew "skhd", restart_service: true
brew "stow"
brew "tmux"
brew "vim"
brew "yarn"

cask "alacritty"
cask "font-fira-code-nerd-font"
